# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: CI

# on:
#   push:
#     branches:
#       - master
#   pull_request:

# jobs:
#   commitlint:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - uses: wagoid/commitlint-github-action@v1.6.0

#   ci:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x]

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up services
#         run: scripts/ci services setup

#       # ===========================================================================================
#       # NPM build and test
#       # ===========================================================================================
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - run: npm ci
#       - run: npm run style-check
#       - run: npm run build --if-present
#       - run: npm test
#       # ===========================================================================================

#       - name: Tear down services
#         run: scripts/ci services teardown
